pipeline {
    agent any
    stages {
        stage('Build Image') {
            steps {
                sh 'gcloud auth configure-docker'
                sh 'docker build -f devops/Dockerfile -t gcr.io/p3-patient-onboarding/patient-onboarding:UATlatest .'
                sh 'docker push gcr.io/p3-patient-onboarding/patient-onboarding:UATlatest'
            }
        }
        stage('Clean Workspace') {
            steps {
                sh 'docker image prune -f'
                cleanWs(deleteDirs:true)
            }
        }
    }
}
