pipeline {
    agent any
    stages {
        stage('Build Image') {
            steps {
                sh 'gcloud auth configure-docker'
                sh 'docker build -t gcr.io/gcplabzamerman/test-flask-server:latest .'
                sh 'docker push gcr.io/gcplabzamerman/test-flask-server:latest'
            }
        }
        stage('Clean Workspace') {
            steps {
                sh 'docker image prune -f'
                cleanWs(deleteDirs:true)
            }
        }
    }
}
